　<?php
$girls = [
    [
        'id' => '1',
        'name' => 'カエラ',
        'age' => '26',
        'img' => '1',
        'time' => '10:30〜15:00',
        'tall' => '164',
        'reserve' => '2000',
        'sun' => true,
        'mon' => true,
        'tue' => false,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '2',
        'name' => 'メロン',
        'age' => '28',
        'img' => 'none',
        'time' => '09:30〜13:00',
        'tall' => '152',
        'reserve' => '1200',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '3',
        'name' => 'ゆうり',
        'age' => '25',
        'img' => '2',
        'time' => '08:00〜10:00',
        'tall' => '168',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '4',
        'name' => 'まつり',
        'age' => '28',
        'img' => 'none',
        'time' => '12:00〜16:00',
        'tall' => '160',
        'reserve' => '3000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '5',
        'name' => 'エルサ',
        'age' => '21',
        'img' => '3',
        'time' => '12:00〜16:00',
        'tall' => '162',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '6',
        'name' => 'めい',
        'age' => '36',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '168',
        'reserve' => '1000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '7',
        'name' => 'まいこ',
        'age' => '42',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '170',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '8',
        'name' => 'べに',
        'age' => '26',
        'img' => '4',
        'time' => '14:00〜20:00',
        'tall' => '170',
        'reserve' => '3000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => true,
    ],
    [
        'id' => '9',
        'name' => 'える',
        'age' => '28',
        'img' => '5',
        'time' => '14:00〜20:00',
        'tall' => '156',
        'reserve' => '2000',
        'sun' => false,
        'mon' => false,
        'tue' => true,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => true,
    ],
    [
        'id' => '10',
        'name' => 'かな',
        'age' => '21',
        'img' => '6',
        'time' => '14:00〜20:00',
        'tall' => '159',
        'reserve' => '2000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => false,
    ],
    [
        'id' => '11',
        'name' => 'あい',
        'age' => '32',
        'img' => '7',
        'time' => '14:00〜20:00',
        'tall' => '159',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => false,
    ],
    [
        'id' => '12',
        'name' => 'せりか',
        'age' => '30',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '165',
        'reserve' => '5000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => false,
    ],
    [
        'id' => '13',
        'name' => 'さくら',
        'age' => '35',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '155',    
        'reserve' => '1000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '14',
        'name' => 'けい',
        'age' => '35',
        'img' => '8',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'reserve' => '3000',
        'sun' => false, 
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '15',
        'name' => 'マイル',
        'age' => '40',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '162',
        'reserve' => '2000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '16',
        'name' => 'えり',
        'age' => '30',
        'img' => '9',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'reserve' => '5000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '17',
        'name' => 'うい',
        'age' => '28',
        'img' => '10',
        'time' => '14:00〜20:00',
        'tall' => '158',
        'reserve' => '2000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => true,
    ],
    [
        'id' => '18',
        'name' => 'まりえ',
        'age' => '21',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '165',
        'reserve' => '3000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '19',
        'name' => 'りいさ',
        'age' => '32',
        'img' => '11',
        'time' => '14:00〜20:00',
        'tall' => '153',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '20',
        'name' => 'ほのか',
        'age' => '39',
        'img' => 'none',
        'time' => '14:00〜20:00',   
        'tall' => '160',
        'reserve' => '1000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
    ],
    [
        'id' => '21',
        'name' => 'ふうか',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '168',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '22',
        'name' => 'ゆり',
        'age' => '29',
        'img' => '12',
        'time' => '14:00〜20:00',
        'tall' => '168',
        'reserve' => '5000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => true,
    ],
    [
        'id' => '23',
        'name' => 'しずか',
        'age' => '25',
        'img' => '13',
        'time' => '14:00〜20:00',
        'tall' => '172',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '24',
        'name' => 'かおる',
        'age' => '22',
        'img' => '14',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'reserve' => '1000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
    ],
    [
        'id' => '25',
        'name' => 'ゆうき',
        'age' => '24',
        'img' => '15',
        'time' => '14:00〜20:00',
        'tall' => '153',
        'reserve' => '2000',
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '26',
        'name' => 'かりん',
        'age' => '29',
        'img' => '16',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'reserve' => '2000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => false,
    ],
    [
        'id' => '27',
        'name' => 'ピーチ',
        'age' => '22',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '159',
        'reserve' => '3000',
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
    ],
    [
        'id' => '28',
        'name' => 'あいく',
        'age' => '25',
        'img' => '17',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'reserve' => '3000',
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => true,
    ],
    [
        'id' => '29',
        'name' => 'メリー',
        'age' => '40',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '168',
        'reserve' => '1000',
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
    ],
    [
        'id' => '30',
        'name' => 'かすみ',
        'age' => '33',
        'img' => '18',
        'time' => '14:00〜20:00',
        'tall' => '168',
        'reserve' => '3000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => true,
    ],       [
        'id' => '31',
        'name' => 'かい',
        'age' => '29',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '158',
        'reserve' => '2000',
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => true,
    ],         [
        'id' => '32',
    ],   
];
?>